% Ziv Yekutieli - ziv.yekutieli@intel.com
%This function recieves two CRs (typically pre and post) which is the
%orginized phase sync' matrices (generated by ZgenerateCrPrePost).
% dCRdtColomn is a set of the matrices of delta, each pixel is in delta
% between the corresponding pixels in each two pair of floors in CrColomn
%##########################################################################
%Rev1- 200709
%Rev2 - 
%##########################################################################

function [MatVecDeltaMean1,MatVecDeltaMean2]= ZgeneratedCRdtByCR2(CrColomn1,CrColomn2,varargin);
%clc; close all; home;

% if isempty(varargin),
%     error('not enough inputs');
% end
[x1,y1,n1] = size(CrColomn1);
[x2,y2,n2] = size(CrColomn2);

if (x1~=x2 || y1~=y2)
     error('Cr Dimentions do not match, seems like wrong number of electrodes was used');
end

%calculate the mean and std of each floor - Pre
for i=1:n1
     [MatMean1(i), MatSTD1(i),MatVec1(:,i)]=ZMatStatistics(CrColomn1(:,:,i));
end
%calculate the mean and std  of the delta between each two floors - Pre
for i=1:n1-1
     MatVecDeltaMean1(i)=mean(abs(MatVec1(:,i+1)-MatVec1(:,i)));
     MatVecDeltaSTD1(i)=std(MatVec1(:,i+1)-MatVec1(:,i));
end
%MatVecDeltaMean1=abs(MatVecDeltaMean1); %if we want to use absolute mean change

%calculate the mean and std of each floor - Post
for i=1:n2
     [MatMean2(i), MatSTD2(i),MatVec2(:,i)]=ZMatStatistics(CrColomn2(:,:,i));
end

%calculate the mean and std  of the delta between each two floors - Pre
% ther first value of the delta is the first Post minus the last Pre
MatVecDeltaMean2(1)=mean(abs(MatVec2(1)-MatVec1(n1)));
MatVecDeltaSTD2(1)=std(MatVec2(1)-MatVec1(n1));
for i=2:n2-1
     MatVecDeltaMean2(i)=mean(abs(MatVec2(:,i+1)-MatVec2(:,i)));
     MatVecDeltaSTD2(i)=std(MatVec2(:,i+1)-MatVec2(:,i));
end
%MatVecDeltaMean2=abs(MatVecDeltaMean2); %if we want to use absolute mean change

%Plotting
c=[length(MatMean1)+1:length(MatMean1)+length(MatMean2)];
d=1.1*max(max(MatMean1),max(MatMean2));
e=1.1*max(max(MatSTD1),max(MatSTD2));
f=length(MatMean1)+length(MatMean2);

c1=[length(MatVecDeltaMean1)+1:length(MatVecDeltaMean1)+length(MatVecDeltaMean2)];
% d1=1.1*max(max(MatVecDeltaMean1),max(MatVecDeltaMean2));
% d2=1.1*min(min(MatVecDeltaMean1),min(MatVecDeltaMean2));
d1=0.1;
d2=0;
e1=1.1*max(max( MatVecDeltaSTD1),max( MatVecDeltaSTD2));
f1=length(MatVecDeltaMean1)+length(MatVecDeltaMean2);
h1=[0:5:floor(f1/2)];

% figure
% subplot(2,2,1)
% plot(MatMean1,'b','LineWidth',2)
% hold on
% plot (c,MatMean2,'r','LineWidth',2)
% ylim([0 d]);
% xlim([0 f]);
% text(length(MatMean1)+0.1,0.9*d,' \leftarrow NCS','FontSize',18)
% line([length(MatMean1) length(MatMean1)],[0 d],'LineStyle','--','LineWidth',6,'Color',[0.7,0.7,0.7]);
% title([varargin{1},' Phase Sync Mean vs. Time']) ;    
% hold off
% 
% subplot(2,2,3)
% plot(MatSTD1,'b','LineWidth',2)
% hold on
% plot (c,MatSTD2,'r','LineWidth',2)
% ylim([0 e]);
% xlim([0 f]);
% text(length(MatSTD1)+0.1,0.9*e,' \leftarrow NCS','FontSize',18)
% line([length(MatSTD1) length(MatSTD1)],[0 e],'LineStyle','--','LineWidth',6,'Color',[0.7,0.7,0.7]);
% title([varargin{1},' Phase Sync STD vs. Time']) ;   
% 
% subplot(2,2,2)
% plot(MatVecDeltaMean1,'b','LineWidth',2)
% hold on
% plot (c1,MatVecDeltaMean2,'r','LineWidth',2)
% ylim([d2 d1]);
% xlim([0 f1]);
% text(length(MatVecDeltaMean1)+0.1,1.2*d2,' \leftarrow NCS','FontSize',18)
% line([length(MatVecDeltaMean1) length(MatVecDeltaMean1)],[d2 d1],'LineStyle','--','LineWidth',6,'Color',[0.7,0.7,0.7]);
% title([varargin{1},' - mean delta between two Phase sync vs. time (dPS/dt)']) ;    
% hold off
% 
% subplot(2,2,4)
% plot(MatVecDeltaSTD1,'b','LineWidth',2)
% hold on
% plot (c1,MatVecDeltaSTD2,'r','LineWidth',2)
% ylim([0 e1]);
% xlim([0 f1]);
% text(length(MatVecDeltaSTD1)+0.1,0.9*e1,' \leftarrow NCS','FontSize',18)
% line([length(MatVecDeltaSTD1) length(MatVecDeltaSTD1)],[0 e],'LineStyle','--','LineWidth',6,'Color',[0.7,0.7,0.7]);
% title([varargin{1},' - std of delta between two Phase sync vs. time']) ;   

%plot only mean change again in a seperate figure
figure
plot(MatVecDeltaMean1,'b','LineWidth',2)
hold on
plot (c1,MatVecDeltaMean2,'r','LineWidth',2)
ylim([d2 d1]);
xlim([0 f1])
%  set(gca,'XTick',[0:floor(f1/c1):f1])
% set(gca,'XTickLabel',{h1})
text(length(MatVecDeltaMean1)-10,(d1-d2)/4,' NCS \rightarrow ','FontSize',12)
%line([0 length(MatVecDeltaMean1)+length(MatVecDeltaMean2)] ,[0 0],'LineStyle','-','LineWidth',1,'Color',[0,0,0]);
line([length(MatVecDeltaMean1) length(MatVecDeltaMean1)],[d2 d1],'LineStyle','--','LineWidth',6,'Color',[0.7,0.7,0.7]);
title([varargin{1},' - mean delta between two Phase sync vs. time (dPS/dt)'],'FontSize',12) ;    
hold off
